language: php

php:
  - 7.1
  - 7.2
  - nightly

before_install:
  - composer self-update

install:
  - composer install --no-interaction

before_script: echo 'zend.assertions = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml